[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'croaker/mustang-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'therubymug/vim-pyte'

[[plugins]]
repo = 'freeo/vim-kalisi'

[[plugins]]
repo = 's3rvac/vim-syntax-yara'
hook_add = '''
'''

# apply colorscheme
[[plugins]]
# preview colorscheme;
#   :Unite -auto-preview colorscheme
repo = 'ujihisa/unite-colorscheme'
# set colorscheme
hook_add = '''
  colorscheme night-owl
  autocmd BufNewFile,BufRead *.yar,*.yara setlocal filetype=yara
'''

