[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
  let g:python_host_prog=$PYENV_ROOT.'/usr/bin/Python'
  let g:python_host_prog=$PYENV_ROOT.'/usr/bin/Python3'
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
  inoremap <expr><Cr> pumvisible() ? deoplete#close_popup() : "\<Cr>"
  inoremap <expr><C-e> deoplete#cancel_popup()
'''
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
hook_add = '''
  let g:jedi#popup_select_first = 0
  let g:jedi#popup_on_dot = 0
  let g:jedi#goto_command = "<leader>d"
  let g:jedi#goto_assignments_command = "<leader>g"
  let g:jedi#goto_definitions_command = ""
  let g:jedi#documentation_command = "K"
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R"
  autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_i = 1
on_ft = 'pu'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_i = 1
on_ft = ['yaml', 'yml']


[[plugins]]
repo = 'elzr/vim-json'
on_i = 1
on_ft = ['json']

[[plugins]]
repo = 'pprovost/vim-ps1'
on_i = 1
on_ft = ['ps1']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_i = 1
on_ft = ['rust']
