[[plugins]]
repo = 'mrk21/yaml-vim'
on_ft = ['yaml']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 's3rvac/vim-syntax-yara'
hook_add = '''
'''
on_ft = ['yara']

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = ['erlang']
